### ISSUE TITLE
-s v.s. -q

### ISSUE THREAD

**Issue by soichih** [brain-life/cli#12]
Some API uses -s for search and some uses -q. It should be consistent. I believe -q is more commonly used for text query by other APIs that does search. 

Like
> https://developers.google.com/apis-explorer/#p/customsearch/v1/search.cse.siterestrict.list
> https://developer.github.com/v3/search/#parameters

I suggest ..

1) Update --search to --query.
2) Use -q for --query
3) Use -s for --skip

**Comment by soichih** [comment]
note for 3).. -s might collide with "--sort" if we add that in the future.. but I guess we could use --order instead?

**Comment by stevengeeky** [comment]
This is implemented
