### ISSUE TITLE
Feature requests & bugfixes: bl-dataset-bidsupload.js

### ISSUE THREAD

**Issue by kathrynalpert** [brain-life/cli#40]
Feature requests:
- handle sessions (longitudinal data) - need another level of nested dirs, e.g.: sub-subject/**ses-session**/anat/sub-sub_ses-session_t1w.nii.gz
- allow links (currently, source data has to be a file not a link) - this might require a feature request or PR to node-archiver to add the -h (--dereference) option to [tar](https://github.com/archiverjs/node-archiver/blob/master/lib/plugins/tar.js)

Bugfixes:
- line 67 should read from participants.tsv
- line 69 should look for "participant_id" column

**Comment by francopestilli** [comment]
@kathrynalpert thanks! @stevengeeky

**Comment by soichih** [comment]
I've added support for sessions, and fixed those bugs. I haven't updated to allow links, however. 

@kathrynalpert What files are linked exactly? The directories, or the files? Or maybe both? Are they symlinks or hardlinks?

**Comment by kathrynalpert** [comment]
[Sorry for my delayed reply - I wasn't receiving notifications, but should be now.]

@soichih In my case, the links are symlinks to files, and it seems that your new code (1.2.38) works with them!

**Comment by kathrynalpert** [comment]
One comment about session handling: The upload works beautifully and the main "datasets" tab has the sessions listed nicely. However, when I'm staging datasets for processing, only the subject ID is visible (see screenshot, I'm talking about how to distinguish between last two datasets), so I have to use timestamp to determine which session I'm selecting. It'd be great if the session were visible here, too.

<img width="628" alt="screen shot 2018-10-11 at 12 56 37 pm" src="https://user-images.githubusercontent.com/313617/46827185-3a5eb680-cd55-11e8-9584-05ebc4dfe5d2.png">

**Comment by soichih** [comment]
@kathrynalpert Thanks for the feature request. I've added session labels on the dataset selecter and a few other places. Please let me know if you notice anywhere else that I should display it. By the way, you can use this repo for posting Brainlife UI issue / requests > https://github.com/brain-life/warehouse/issues

**Comment by kathrynalpert** [comment]
Fabulous changes! I'm closing this issue and will make UI requests there in future.
